title: Kafka on The Shore 
author: Alex Padayao
email: padayaoalex@outlook.com
description: > # this means to ignore newlines until "baseurl:"
This is my review for Kafka on The Shore by Haruki Murakami
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  apadayao # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
